#!/bin/bash
#SBATCH --account=subramanianh
#SBATCH --qos=subramanianh
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --mem-per-cpu=8192mb
#SBATCH --gres=gpu:a100:1
#SBATCH --time=00:30:00
#SBATCH --job-name=transformer
#SBATCH --mail-type=ALL
#SBATCH --mail-user=<yxu055@fiu.edu>
#SBATCH --output=log
#SBATCH --error=err

module purge

pwd; hostname; date

module load ngc-pytorch

python main2.py
python main2.py --use-te
python main2.py --epochs 5 --save-model
